"""Add a feedback field.

Revision ID: 299a66083d67
Revises: 5a723f673cf3
Create Date: 2025-10-11 15:35:34.828350

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '299a66083d67'
down_revision = '5a723f673cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizattempt', sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizattempt', 'feedback')
    # ### end Alembic commands ###
