"""Add update at and create at fields.

Revision ID: 30d96ddd4938
Revises: 2948e66c0c53
Create Date: 2025-09-22 19:40:39.241339

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '30d96ddd4938'
down_revision = '2948e66c0c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('course', sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_index(op.f('ix_course_created_at'), 'course', ['created_at'], unique=False)
    op.create_index(op.f('ix_course_owner_id'), 'course', ['owner_id'], unique=False)
    op.create_index(op.f('ix_course_uploaded_at'), 'course', ['uploaded_at'], unique=False)
    op.add_column('document', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'created_at')
    op.drop_index(op.f('ix_course_uploaded_at'), table_name='course')
    op.drop_index(op.f('ix_course_owner_id'), table_name='course')
    op.drop_index(op.f('ix_course_created_at'), table_name='course')
    op.drop_column('course', 'uploaded_at')
    op.drop_column('course', 'created_at')
    # ### end Alembic commands ###
