"""Add a feedback field.

Revision ID: 5a723f673cf3
Revises: 64343f21e9a8
Create Date: 2025-10-11 15:31:20.510029

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a723f673cf3'
down_revision = '64343f21e9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('podcast')
    op.add_column('quiz', sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'feedback')
    op.create_table('podcast',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('audio_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('storage_backend', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('podcast_course_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('podcast_pkey'))
    )
    # ### end Alembic commands ###
