"""Update relationships.

Revision ID: d2132ce05cf8
Revises: 299a66083d67
Create Date: 2025-10-11 18:55:54.930042

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd2132ce05cf8'
down_revision = '299a66083d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('course_id', sa.Uuid(), nullable=True))
    op.add_column('chunk', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('chunk', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'chunk', 'course', ['course_id'], ['id'])
    op.add_column('quiz', sa.Column('document_id', sa.Uuid(), nullable=True))
    op.add_column('quiz', sa.Column('course_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'quiz', 'course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'quiz', 'document', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz', type_='foreignkey')
    op.drop_constraint(None, 'quiz', type_='foreignkey')
    op.drop_column('quiz', 'course_id')
    op.drop_column('quiz', 'document_id')
    op.drop_constraint(None, 'chunk', type_='foreignkey')
    op.drop_column('chunk', 'updated_at')
    op.drop_column('chunk', 'created_at')
    op.drop_column('chunk', 'course_id')
    # ### end Alembic commands ###
